// Generated by beansc bindgen for arm64-apple-darwin.

package cortado_skia

pub extern "C" fn ctd_skia_new() -> RawPtr<u8>
pub extern "C" fn ctd_skia_delete(context: RawPtr<u8>)
pub extern "C" fn ctd_skia_backend(context: RawPtr<u8>) -> i32
pub extern "C" fn ctd_skia_select_backend(context: RawPtr<u8>, preferred: i32) -> i32
pub extern "C" fn ctd_skia_recover_software(context: RawPtr<u8>) -> i32
pub extern "C" fn ctd_skia_begin(context: RawPtr<u8>, width: f64, height: f64, scale: f64, rgba: u32) -> i32
pub extern "C" fn ctd_skia_end(context: RawPtr<u8>) -> i32
pub extern "C" fn ctd_skia_save(context: RawPtr<u8>) -> i32
pub extern "C" fn ctd_skia_restore(context: RawPtr<u8>) -> i32
pub extern "C" fn ctd_skia_translate(context: RawPtr<u8>, x: f64, y: f64) -> i32
pub extern "C" fn ctd_skia_rotate(context: RawPtr<u8>, degrees: f64) -> i32
pub extern "C" fn ctd_skia_scale(context: RawPtr<u8>, x: f64, y: f64) -> i32
pub extern "C" fn ctd_skia_clip(context: RawPtr<u8>, x: f64, y: f64, width: f64, height: f64, radius: f64) -> i32
pub extern "C" fn ctd_skia_rect(context: RawPtr<u8>, x: f64, y: f64, width: f64, height: f64, radius: f64, rgba: u32, stroke: f64) -> i32
pub extern "C" fn ctd_skia_ellipse(context: RawPtr<u8>, x: f64, y: f64, width: f64, height: f64, fill: u32, outline: u32, stroke: f64) -> i32
pub extern "C" fn ctd_skia_path(context: RawPtr<u8>, data: RawPtr<i8>, length: i32, fill: u32, outline: u32, stroke: f64) -> i32
pub extern "C" fn ctd_skia_visual(context: RawPtr<u8>, kind: i32, x: f64, y: f64, width: f64, height: f64, data: RawPtr<i8>, length: i32, fill: u32, outline: u32, stroke: f64, gradient_start: u32, gradient_end: u32, gradient_enabled: i32, shadow_color: u32, shadow_blur: f64, shadow_dx: f64, shadow_dy: f64, clip_radius: f64) -> i32
pub extern "C" fn ctd_skia_image_new(context: RawPtr<u8>, source: RawPtr<i8>, length: i32) -> u64
pub extern "C" fn ctd_skia_image_release(context: RawPtr<u8>, image: u64) -> i32
pub extern "C" fn ctd_skia_image_size(context: RawPtr<u8>, image: u64, size: RawPtr<f64>) -> i32
pub extern "C" fn ctd_skia_image_draw(context: RawPtr<u8>, image: u64, x: f64, y: f64, width: f64, height: f64) -> i32
pub extern "C" fn ctd_skia_paragraph_new(context: RawPtr<u8>, text: RawPtr<i8>, length: i32, size: f64, width: f64, rgba: u32) -> u64
pub extern "C" fn ctd_skia_paragraph_release(context: RawPtr<u8>, paragraph: u64) -> i32
pub extern "C" fn ctd_skia_paragraph_size(context: RawPtr<u8>, paragraph: u64, size: RawPtr<f64>) -> i32
pub extern "C" fn ctd_skia_paragraph_paint(context: RawPtr<u8>, paragraph: u64, x: f64, y: f64) -> i32
pub extern "C" fn ctd_skia_paragraph_hit(context: RawPtr<u8>, paragraph: u64, x: f64, y: f64) -> i32
pub extern "C" fn ctd_skia_paragraph_caret(context: RawPtr<u8>, paragraph: u64, offset: i32, rect: RawPtr<f64>) -> i32
pub extern "C" fn ctd_skia_paragraph_selection(context: RawPtr<u8>, paragraph: u64, first: i32, last: i32, out: RawPtr<f64>, capacity: i32) -> i32
pub extern "C" fn ctd_skia_graphemes(context: RawPtr<u8>, text: RawPtr<i8>, length: i32, out: RawPtr<i32>, capacity: i32) -> i32
pub extern "C" fn ctd_skia_pixels(context: RawPtr<u8>, size: RawPtr<f64>, out: RawPtr<i8>, capacity: i32) -> i32
pub extern "C" fn ctd_skia_png(context: RawPtr<u8>, path: RawPtr<i8>, length: i32) -> i32
