// Generated by beansc bindgen for arm64-apple-darwin.

package host

pub extern "C" struct CtdEvent {
    pub kind: u32
    pub modifiers: u32
    pub target: u64
    pub index: i64
    pub token: i64
    pub x: f64
    pub y: f64
    pub width: f64
    pub height: f64
    pub text: RawPtr<i8>
    pub text_len: i32
}

pub extern "C" fn ctd_abi_version() -> u32
pub extern "C" fn ctd_init(want_abi: u32) -> i32
pub extern "C" fn ctd_app_set_role(role: i32) -> i32
pub extern "C" fn ctd_set_event_sink(sink: fn(RawPtr<u8>, RawPtr<CtdEvent>), context: RawPtr<u8>) -> i32
pub extern "C" fn ctd_shutdown()
pub extern "C" fn ctd_app_run()
pub extern "C" fn ctd_app_stop()
pub extern "C" fn ctd_app_run_for(seconds: f64) -> i32
pub extern "C" fn ctd_post(token: i64)
pub extern "C" fn ctd_capability(capability: i32) -> i32
pub extern "C" fn ctd_surface_new(width: f64, height: f64) -> u64
pub extern "C" fn ctd_surface_set_title(surface: u64, utf8: RawPtr<i8>, len: i32) -> i32
pub extern "C" fn ctd_surface_title(surface: u64, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_surface_set_root(surface: u64, root: u64) -> i32
pub extern "C" fn ctd_surface_root(surface: u64) -> u64
pub extern "C" fn ctd_surface_content_size(surface: u64, out_size: RawPtr<f64>) -> i32
pub extern "C" fn ctd_surface_show(surface: u64) -> i32
pub extern "C" fn ctd_surface_close(surface: u64) -> i32
pub extern "C" fn ctd_surface_visible(surface: u64) -> i32
pub extern "C" fn ctd_clock_start(surface: u64, token: i64) -> i32
pub extern "C" fn ctd_clock_stop(surface: u64) -> i32
pub extern "C" fn ctd_clock_state(surface: u64, out: RawPtr<f64>) -> i32
pub extern "C" fn ctd_clock_step(surface: u64, seconds: f64) -> i32
pub extern "C" fn ctd_widget_supports(kind: i32) -> i32
pub extern "C" fn ctd_widget_new(kind: i32) -> u64
pub extern "C" fn ctd_widget_kind(widget: u64) -> i32
pub extern "C" fn ctd_widget_alive(widget: u64) -> i32
pub extern "C" fn ctd_widget_release(widget: u64) -> i32
pub extern "C" fn ctd_view_add_child(parent: u64, child: u64, index: i32) -> i32
pub extern "C" fn ctd_view_remove_child(parent: u64, child: u64) -> i32
pub extern "C" fn ctd_view_move_child(parent: u64, from: i32, to: i32) -> i32
pub extern "C" fn ctd_view_child_count(parent: u64, out: RawPtr<i32>) -> i32
pub extern "C" fn ctd_view_child_at(parent: u64, index: i32) -> u64
pub extern "C" fn ctd_view_parent(child: u64) -> u64
pub extern "C" fn ctd_view_surface(widget: u64) -> u64
pub extern "C" fn ctd_view_set_frame(widget: u64, x: f64, y: f64, width: f64, height: f64) -> i32
pub extern "C" fn ctd_view_frame(widget: u64, out_frame: RawPtr<f64>) -> i32
pub extern "C" fn ctd_view_measure(widget: u64, avail_width: f64, avail_height: f64, out_size: RawPtr<f64>) -> i32
pub extern "C" fn ctd_view_content_inset(widget: u64, out_inset: RawPtr<f64>) -> i32
pub extern "C" fn ctd_set_string(widget: u64, key: i32, utf8: RawPtr<i8>, len: i32) -> i32
pub extern "C" fn ctd_get_string(widget: u64, key: i32, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_set_text(widget: u64, utf8: RawPtr<i8>, len: i32) -> i32
pub extern "C" fn ctd_get_text(widget: u64, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_set_int(widget: u64, key: i32, value: i64) -> i32
pub extern "C" fn ctd_get_int(widget: u64, key: i32, out: RawPtr<i64>) -> i32
pub extern "C" fn ctd_set_real(widget: u64, key: i32, value: f64) -> i32
pub extern "C" fn ctd_get_real(widget: u64, key: i32, out: RawPtr<f64>) -> i32
pub extern "C" fn ctd_anim_new(widget: u64, property: i32) -> u64
pub extern "C" fn ctd_anim_from_real(anim: u64, value: f64) -> i32
pub extern "C" fn ctd_anim_to_real(anim: u64, value: f64) -> i32
pub extern "C" fn ctd_anim_duration(anim: u64, seconds: f64) -> i32
pub extern "C" fn ctd_anim_delay(anim: u64, seconds: f64) -> i32
pub extern "C" fn ctd_anim_curve(anim: u64, curve: i32) -> i32
pub extern "C" fn ctd_anim_start(anim: u64, token: i64) -> i32
pub extern "C" fn ctd_anim_cancel(anim: u64) -> i32
pub extern "C" fn ctd_gpu_shader_langs() -> u32
pub extern "C" fn ctd_gpu_device_new() -> u64
pub extern "C" fn ctd_gpu_device_name(device: u64, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_gpu_device_limit(device: u64, which: i32, out: RawPtr<f64>) -> i32
pub extern "C" fn ctd_gpu_release(object: u64) -> i32
pub extern "C" fn ctd_gpu_buffer_new(device: u64, data: RawPtr<f32>, count: i32) -> u64
pub extern "C" fn ctd_gpu_buffer_write(buffer: u64, first: i32, data: RawPtr<f32>, count: i32) -> i32
pub extern "C" fn ctd_gpu_buffer_count(buffer: u64, out: RawPtr<i32>) -> i32
pub extern "C" fn ctd_gpu_target_new(device: u64, width: i32, height: i32) -> u64
pub extern "C" fn ctd_gpu_target_read(target: u64, out_size: RawPtr<f64>, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_gpu_shader_new(device: u64, language: i32, source: RawPtr<i8>, len: i32) -> u64
pub extern "C" fn ctd_gpu_shader_problem(device: u64, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_gpu_pipeline_new(shader: u64, vertex: RawPtr<i8>, vertex_len: i32, fragment: RawPtr<i8>, fragment_len: i32) -> u64
pub extern "C" fn ctd_gpu_pipeline_attr(pipeline: u64, index: i32, floats: i32, offset: i32) -> i32
pub extern "C" fn ctd_gpu_pipeline_stride(pipeline: u64, floats: i32) -> i32
pub extern "C" fn ctd_gpu_pipeline_blend(pipeline: u64, blend: i32) -> i32
pub extern "C" fn ctd_gpu_pipeline_build(pipeline: u64) -> i32
pub extern "C" fn ctd_gpu_pass_begin(target: u64, r: f64, g: f64, b: f64, a: f64) -> u64
pub extern "C" fn ctd_gpu_pass_pipeline(pass: u64, pipeline: u64) -> i32
pub extern "C" fn ctd_gpu_pass_vertices(pass: u64, buffer: u64) -> i32
pub extern "C" fn ctd_gpu_pass_uniform(pass: u64, data: RawPtr<f32>, count: i32) -> i32
pub extern "C" fn ctd_gpu_pass_draw(pass: u64, shape: i32, first: i32, count: i32) -> i32
pub extern "C" fn ctd_gpu_pass_end(pass: u64) -> i32
pub extern "C" fn ctd_gpu_canvas_attach(widget: u64, device: u64) -> i32
pub extern "C" fn ctd_gpu_canvas_next(widget: u64) -> u64
pub extern "C" fn ctd_gpu_pass_present(pass: u64) -> i32
pub extern "C" fn ctd_gpu_pipeline_pixels(pipeline: u64, pixels: i32) -> i32
pub extern "C" fn ctd_menu_new(title: RawPtr<i8>, len: i32) -> u64
pub extern "C" fn ctd_menu_add_item(menu: u64, title: RawPtr<i8>, title_len: i32, key: RawPtr<i8>, key_len: i32, role: i32, token: i64) -> i32
pub extern "C" fn ctd_menu_add_separator(menu: u64) -> i32
pub extern "C" fn ctd_menu_add_submenu(menu: u64, child: u64) -> i32
pub extern "C" fn ctd_menu_item_count(menu: u64, out: RawPtr<i32>) -> i32
pub extern "C" fn ctd_menu_item_title(menu: u64, index: i32, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_menu_item_key(menu: u64, index: i32, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_menu_set_bar(menu: u64) -> i32
pub extern "C" fn ctd_menu_set_enabled(menu: u64, token: i64, on: i32) -> i32
pub extern "C" fn ctd_menu_invoke(menu: u64, token: i64) -> i32
pub extern "C" fn ctd_toolbar_set(surface: u64, menu: u64) -> i32
pub extern "C" fn ctd_toolbar_clear(surface: u64) -> i32
pub extern "C" fn ctd_toolbar_count(surface: u64, out: RawPtr<i32>) -> i32
pub extern "C" fn ctd_popover_new(content: u64, width: f64, height: f64) -> u64
pub extern "C" fn ctd_popover_show(popover: u64, anchor: u64, edge: i32) -> i32
pub extern "C" fn ctd_popover_close(popover: u64) -> i32
pub extern "C" fn ctd_popover_shown(popover: u64, out: RawPtr<i32>) -> i32
pub extern "C" fn ctd_popover_release(popover: u64) -> i32
pub extern "C" fn ctd_dialog_open(parent: u64, kind: i32, title: RawPtr<i8>, title_len: i32, body: RawPtr<i8>, body_len: i32, token: i64) -> i32
pub extern "C" fn ctd_appearance() -> i32
pub extern "C" fn ctd_surface_scale(surface: u64, out: RawPtr<f64>) -> i32
pub extern "C" fn ctd_font_family(role: i32, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_font_size(role: i32, out: RawPtr<f64>) -> i32
pub extern "C" fn ctd_items_clear(widget: u64) -> i32
pub extern "C" fn ctd_items_add(widget: u64, utf8: RawPtr<i8>, len: i32) -> i32
pub extern "C" fn ctd_items_count(widget: u64, out: RawPtr<i32>) -> i32
pub extern "C" fn ctd_tab_set_label(widget: u64, index: i32, utf8: RawPtr<i8>, len: i32) -> i32
pub extern "C" fn ctd_tab_label(widget: u64, index: i32, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_items_at(widget: u64, index: i32, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_set_table_source(source: fn(RawPtr<u8>, u64, i32, i32, RawPtr<i8>, i32) -> i32, context: RawPtr<u8>) -> i32
pub extern "C" fn ctd_table_columns(table: u64, count: i32) -> i32
pub extern "C" fn ctd_table_column_title(table: u64, column: i32, utf8: RawPtr<i8>, len: i32) -> i32
pub extern "C" fn ctd_table_column_width(table: u64, column: i32, points: f64) -> i32
pub extern "C" fn ctd_table_rows(table: u64, count: i32) -> i32
pub extern "C" fn ctd_table_reload(table: u64) -> i32
pub extern "C" fn ctd_table_cell(table: u64, row: i32, column: i32, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_table_selected(table: u64, out: RawPtr<i32>) -> i32
pub extern "C" fn ctd_table_select(table: u64, row: i32) -> i32
pub extern "C" fn ctd_permission_status(what: i32, out: RawPtr<i32>) -> i32
pub extern "C" fn ctd_permission_request(what: i32, token: i64) -> i32
pub extern "C" fn ctd_native_class(widget: u64, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_a11y_role(widget: u64, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_snapshot(widget: u64, out_size: RawPtr<f64>, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_widget_activate(widget: u64) -> i32
pub extern "C" fn ctd_widget_synth_value(widget: u64, index: i64, value: f64) -> i32
pub extern "C" fn ctd_widget_synth_text(widget: u64, utf8: RawPtr<i8>, len: i32) -> i32
