// Generated by beansc bindgen for arm64-apple-darwin.

package host

pub extern "C" struct CtdEvent {
    pub kind: u32
    pub modifiers: u32
    pub target: u64
    pub index: i64
    pub token: i64
    pub x: f64
    pub y: f64
    pub width: f64
    pub height: f64
}

pub extern "C" fn ctd_abi_version() -> u32
pub extern "C" fn ctd_init(want_abi: u32) -> i32
pub extern "C" fn ctd_app_set_role(role: i32) -> i32
pub extern "C" fn ctd_set_event_sink(sink: fn(RawPtr<u8>, RawPtr<CtdEvent>), context: RawPtr<u8>) -> i32
pub extern "C" fn ctd_shutdown()
pub extern "C" fn ctd_app_run()
pub extern "C" fn ctd_app_stop()
pub extern "C" fn ctd_post(token: i64)
pub extern "C" fn ctd_capability(capability: i32) -> i32
pub extern "C" fn ctd_surface_new(width: f64, height: f64) -> u64
pub extern "C" fn ctd_surface_set_title(surface: u64, utf8: RawPtr<i8>, len: i32) -> i32
pub extern "C" fn ctd_surface_title(surface: u64, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_surface_set_root(surface: u64, root: u64) -> i32
pub extern "C" fn ctd_surface_root(surface: u64) -> u64
pub extern "C" fn ctd_surface_content_size(surface: u64, out_size: RawPtr<f64>) -> i32
pub extern "C" fn ctd_surface_show(surface: u64) -> i32
pub extern "C" fn ctd_surface_close(surface: u64) -> i32
pub extern "C" fn ctd_surface_visible(surface: u64) -> i32
pub extern "C" fn ctd_widget_new(kind: i32) -> u64
pub extern "C" fn ctd_widget_kind(widget: u64) -> i32
pub extern "C" fn ctd_widget_alive(widget: u64) -> i32
pub extern "C" fn ctd_widget_release(widget: u64) -> i32
pub extern "C" fn ctd_view_add_child(parent: u64, child: u64, index: i32) -> i32
pub extern "C" fn ctd_view_remove_child(parent: u64, child: u64) -> i32
pub extern "C" fn ctd_view_move_child(parent: u64, from: i32, to: i32) -> i32
pub extern "C" fn ctd_view_child_count(parent: u64, out: RawPtr<i32>) -> i32
pub extern "C" fn ctd_view_child_at(parent: u64, index: i32) -> u64
pub extern "C" fn ctd_view_parent(child: u64) -> u64
pub extern "C" fn ctd_view_set_frame(widget: u64, x: f64, y: f64, width: f64, height: f64) -> i32
pub extern "C" fn ctd_view_frame(widget: u64, out_frame: RawPtr<f64>) -> i32
pub extern "C" fn ctd_view_measure(widget: u64, avail_width: f64, avail_height: f64, out_size: RawPtr<f64>) -> i32
pub extern "C" fn ctd_set_text(widget: u64, utf8: RawPtr<i8>, len: i32) -> i32
pub extern "C" fn ctd_get_text(widget: u64, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_set_int(widget: u64, key: i32, value: i64) -> i32
pub extern "C" fn ctd_get_int(widget: u64, key: i32, out: RawPtr<i64>) -> i32
pub extern "C" fn ctd_set_real(widget: u64, key: i32, value: f64) -> i32
pub extern "C" fn ctd_get_real(widget: u64, key: i32, out: RawPtr<f64>) -> i32
pub extern "C" fn ctd_native_class(widget: u64, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_a11y_role(widget: u64, out: RawPtr<i8>, cap: i32) -> i32
pub extern "C" fn ctd_widget_activate(widget: u64) -> i32
